port: 7880
bind_addresses:
    - ""
rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 60000
    use_external_ip: true
    enable_loopback_candidate: false
redis:
    address: cohost-gateway-backbone.nkegqk.ng.0001.use1.cache.amazonaws.com:6379
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
turn:
    enabled: true
    domain: cohost.transcode.reup.live
    tls_port: 5349
    udp_port: 3478
    external_tls: true
keys:
    APILmgQYUbevQrh: 5k70P9nctIMAoYCnfAnYD8GVDshSImXN1P2w2ZRUPIc
room:
    auto_create: false
    max_participants: 4
    departure_timeout: 120
webhook:
    api_key: APILmgQYUbevQrh
    urls:
      - 'http://127.0.0.1:4099/live/webhook'
